<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-E1E9EHH" name="selenium4features.Dockergrid" tests="1" failures="0" timestamp="25 Oct 2019 18:27:12 GMT" time="16.806" errors="1">
  <testcase name="testgrid" time="16.806" classname="selenium4features.Dockergrid">
    <error type="org.openqa.selenium.remote.UnreachableBrowserException" message="Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: &#039;4.0.0-alpha-3&#039;, revision: &#039;8c567de6dc&#039;
System info: host: &#039;DESKTOP-E1E9EHH&#039;, ip: &#039;192.168.99.1&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_201&#039;
Driver info: driver.version: RemoteWebDriver">
      <![CDATA[org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.Build info: version: '4.0.0-alpha-3', revision: '8c567de6dc'System info: host: 'DESKTOP-E1E9EHH', ip: '192.168.99.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'Driver info: driver.version: RemoteWebDriverat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:597)at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:210)at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:143)at selenium4features.Dockergrid.testgrid(Dockergrid.java:33)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)Caused by: java.io.UncheckedIOException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:4546at org.openqa.selenium.remote.http.okhttp.OkHandler.makeCall(OkHandler.java:63)at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)at org.openqa.selenium.remote.http.okhttp.OkHandler.execute(OkHandler.java:52)at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)at org.openqa.selenium.remote.http.okhttp.OkHttpClient.execute(OkHttpClient.java:45)at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:106)at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:139)at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:576)... 29 moreCaused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:4546at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:270)at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:176)at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:236)at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)at okhttp3.RealCall.execute(RealCall.kt:66)at org.openqa.selenium.remote.http.okhttp.OkHandler.makeCall(OkHandler.java:60)... 39 moreCaused by: java.net.ConnectException: Connection refused: connectat java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)at java.net.Socket.connect(Socket.java:589)at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:126)at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:268)... 58 more]]>
    </error>
  </testcase> <!-- testgrid -->
</testsuite> <!-- selenium4features.Dockergrid -->
